# Function to combine adjacent segments with common
# Linkage into single blocks.
# Input is `SegmentGR`, from `changeList` output from runChangepointOnSE
# Discards MegLog2HetHom estimates
#' Reduce adjacent segments with common linkage
#'
#' This function merges adjacent segments that have the same chromosomal
#' linkage (i.e. autosomal, X, or Y) into a single unified segment. The main
#' purpose is to reduce adjacent segments detectd by Changepoint that may have
#' different means but are still considered to have the same sex-chromosome or
#' autosomal linkage.
#'
#' @param SegmentGR A GenomicRanges object that is produced from analyzing
#' sex-linkage with the function \code{runChangepointOnSE}.
#'
#' @return A GenomicRanges object.
#' @export
#'
#' @examples
reduceSegments <- function( SegmentGR ) {
   # outGR <- unlist(GenomicRanges::reduce(split(SegmentGR, ~Linkage)))
   splitGR <- GenomicRanges::split(SegmentGR, ~Linkage)
   reducedGR <- GenomicRanges::reduce(splitGR)
   outGR <- unlist(reducedGR)
   outGR$Linkage <- names(outGR)
   names(outGR) <- NULL
   return(sort(outGR))
}





#' Merge segments for all chromosomes
#'
#' Operating on the list generated by \code{runChangepointOnSE}, this function
#' merges all adjacent ranges with the linkage type (e.g. Autosomal, X|Z, or
#' Y|W). It produces the minimum set of coordinate ranges to capture blocks of
#' linkage inferred by Changepoint analysis.
#'
#' In many cases, especially for Y|W chromosome, coverage ratios vary substantially
#' but  still consistently exceed the threshold for being called sex-linked.
#' This can result in many adjacent segments that are distinguished
#' by having different means, but are all still considered Y|W linked, for instance.
#' This function will merged those adjacent segments into a single range, though
#' the mean log2(Hom:Het) ratio is removed as a result.
#'
#' @param changeList The list output by \code{runChangepointOnSE}
#' @param asDF Logical. If TRUE, returns results formatted as a dataframe. The default
#' value FALSE returns formatted as a GenomicRanges List.
#'
#' @return Either a dataframe or GenomicRanges (default) object containing the
#' minimum set of ranges needed to indicate autosomale of sex-chromosome linkage
#' of segments detected by changepoint analysis.
#' @export
#'
#' @examples
mergeSegments <- function( changeList, asDF = FALSE ) {
   # generate list of GRanges objects with adjacent linkage types reduced
   outGRL <- lapply(changeList, FUN = function(x) {reduceSegments(x[[2]])})
   outGRL <- GenomicRanges::GRangesList(outGRL)

   if (asDF) {
      return(data.frame(outGRL))
   } else {
      return(outGRL)
   }
}

