
#' Generate Normalization Factors
#'
#' The \code{getNormFactors} function creates normalization factors for each sample in the \code{SummarizedExperiment} object. It creates two types of normalization factors: total counts
#' of each sample and the median value of counts across windows. These values are
#' added to the \code{SummarizedExperiment} object that is returned.
#'
#' This is primarily a utility function used by \code{normalizeCounts} and should
#' not normally be called directly in routine usage of ZWYX.
#'
#' @param se a \code{SummarizedExperiment} object created for analysis in ZWYX
#'
#' @return the same \code{SummarizedExperiment} object as input, with additional
#' column data entries for \code{totalcounts} and \code{windowmedian}
#' @export
#'
#' @examples
getNormFactors <- function(se) {
   readcounts <- SummarizedExperiment::assay(se, "counts")
   totalcounts <- colSums(readcounts, na.rm = TRUE)
   windowmedian <- apply(X=readcounts, MARGIN = 2, FUN = stats::median, na.rm = TRUE)
   SummarizedExperiment::colData(se)$totalReads <- totalcounts
   SummarizedExperiment::colData(se)$windowmedian <- windowmedian
   return(se)
}



#' Normalize Read Counts
#'
#' The \code{normalizeCounts} function enerates normalized read count values in each window for a
#' \code{SummarizedExperiment} object. Read counts can be normalized either by total
#' reads per sample or the median read count across windows. A matrix of normalized, rescaled
#' read counts is appended as an assay to the input \code{SummarizedExperiment} object.
#'
#'
#' @param se A \code{SummarizedExperiment} object created for analysis in ZWYX
#' @param method The method used for normalization. A character value either
#' \code{"totalreads"} or \code{"windowmedian"}. If \code{"totalreads"}, each
#' window's read count in a sample is divided by the total read count across windows
#' in the sample.
#' If \code{"windowmedian"}, each window's read count in a sample is divided by
#' the median of all window counts in the sample.
#' @param scale A single numeric value by which normalized window read count values are
#' multiplied in order rescale values after normalization to be a "pretty" number.
#' Here "pretty" simply means not an overlay small or large number. Default value
#' is \code{NA},
#' which will use \code{1000} for \code{"totalreads"} normalization or \code{1e8}
#' for \code{"windowmedian"} normalization.
#'
#'
#' @return The function returns a modified version of the same
#' \code{SummarizedExperiment} (SE) object that was input. The returned SE object
#' has two additions. First, the column data includes entries for
#' \code{totalcounts} or \code{windowmedian}, corresponding to which method was
#' used and generated by the \code{getNormFactors}
#' function. Second, and more importantly, an additional assay matrix is appended
#' to the SE object. This appended assay  matrix is named \code{normdata} and
#' contains the normalized and rescaled read count values, which will be used
#' for downstream analyses in ZWYX.
#' @export
#'
#' @examples
normalizeCounts <-function(se, method = "totalreads", scale = NA) {
   if (! any(method == c("totalreads", "windowmedian"))) {
      stop("method must be either 'totalreads' or 'windowmedian'")
   }
   se <- getNormFactors(se)  # add column sums and medians to
   readcounts <- SummarizedExperiment::assay(se, "counts")
   if (method == "totalreads") {
      normfactor <- SummarizedExperiment::colData(se)$totalReads
      if (is.na(scale)) {scale <-  1e8}
   }
   if (method == "windowmedian") {
      normfactor <-  SummarizedExperiment::colData(se)$windowmedian
      if (is.na(scale)) {scale <-  1e3}
   }
   normcounts <- t(t(readcounts)/normfactor) * scale
   SummarizedExperiment::assays(se, withDimnames = FALSE)[["normdata"]] <- normcounts
   SummarizedExperiment::colData(se)$NormMethod <- method
   return(se)
}

